/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerasIzolasyonBornovaRouteImport } from './routes/teras-izolasyon-bornova'
import { Route as SuYalitimiKarsiyakaRouteImport } from './routes/su-yalitimi-karsiyaka'
import { Route as ProjelerimizRouteImport } from './routes/projelerimiz'
import { Route as IzolasyonFirmasiBornovaRouteImport } from './routes/izolasyon-firmasi-bornova'
import { Route as IletisimRouteImport } from './routes/iletisim'
import { Route as HizmetlerRouteImport } from './routes/hizmetler'
import { Route as HavuzIzolasyonUrlaRouteImport } from './routes/havuz-izolasyon-urla'
import { Route as HavuzIzolasyonCesmeRouteImport } from './routes/havuz-izolasyon-cesme'
import { Route as HakkimizdaRouteImport } from './routes/hakkimizda'
import { Route as EpoksiZeminCigliRouteImport } from './routes/epoksi-zemin-cigli'
import { Route as CatiIzolasyonKarsiyakaRouteImport } from './routes/cati-izolasyon-karsiyaka'
import { Route as CatiIzolasyonBornovaRouteImport } from './routes/cati-izolasyon-bornova'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjelerimizSlugRouteImport } from './routes/projelerimiz_.$slug'
import { Route as HizmetlerSlugRouteImport } from './routes/hizmetler_.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog_.$slug'

const TerasIzolasyonBornovaRoute = TerasIzolasyonBornovaRouteImport.update({
  id: '/teras-izolasyon-bornova',
  path: '/teras-izolasyon-bornova',
  getParentRoute: () => rootRouteImport,
} as any)
const SuYalitimiKarsiyakaRoute = SuYalitimiKarsiyakaRouteImport.update({
  id: '/su-yalitimi-karsiyaka',
  path: '/su-yalitimi-karsiyaka',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjelerimizRoute = ProjelerimizRouteImport.update({
  id: '/projelerimiz',
  path: '/projelerimiz',
  getParentRoute: () => rootRouteImport,
} as any)
const IzolasyonFirmasiBornovaRoute = IzolasyonFirmasiBornovaRouteImport.update({
  id: '/izolasyon-firmasi-bornova',
  path: '/izolasyon-firmasi-bornova',
  getParentRoute: () => rootRouteImport,
} as any)
const IletisimRoute = IletisimRouteImport.update({
  id: '/iletisim',
  path: '/iletisim',
  getParentRoute: () => rootRouteImport,
} as any)
const HizmetlerRoute = HizmetlerRouteImport.update({
  id: '/hizmetler',
  path: '/hizmetler',
  getParentRoute: () => rootRouteImport,
} as any)
const HavuzIzolasyonUrlaRoute = HavuzIzolasyonUrlaRouteImport.update({
  id: '/havuz-izolasyon-urla',
  path: '/havuz-izolasyon-urla',
  getParentRoute: () => rootRouteImport,
} as any)
const HavuzIzolasyonCesmeRoute = HavuzIzolasyonCesmeRouteImport.update({
  id: '/havuz-izolasyon-cesme',
  path: '/havuz-izolasyon-cesme',
  getParentRoute: () => rootRouteImport,
} as any)
const HakkimizdaRoute = HakkimizdaRouteImport.update({
  id: '/hakkimizda',
  path: '/hakkimizda',
  getParentRoute: () => rootRouteImport,
} as any)
const EpoksiZeminCigliRoute = EpoksiZeminCigliRouteImport.update({
  id: '/epoksi-zemin-cigli',
  path: '/epoksi-zemin-cigli',
  getParentRoute: () => rootRouteImport,
} as any)
const CatiIzolasyonKarsiyakaRoute = CatiIzolasyonKarsiyakaRouteImport.update({
  id: '/cati-izolasyon-karsiyaka',
  path: '/cati-izolasyon-karsiyaka',
  getParentRoute: () => rootRouteImport,
} as any)
const CatiIzolasyonBornovaRoute = CatiIzolasyonBornovaRouteImport.update({
  id: '/cati-izolasyon-bornova',
  path: '/cati-izolasyon-bornova',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjelerimizSlugRoute = ProjelerimizSlugRouteImport.update({
  id: '/projelerimiz_/$slug',
  path: '/projelerimiz/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HizmetlerSlugRoute = HizmetlerSlugRouteImport.update({
  id: '/hizmetler_/$slug',
  path: '/hizmetler/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog_/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/cati-izolasyon-bornova': typeof CatiIzolasyonBornovaRoute
  '/cati-izolasyon-karsiyaka': typeof CatiIzolasyonKarsiyakaRoute
  '/epoksi-zemin-cigli': typeof EpoksiZeminCigliRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/havuz-izolasyon-cesme': typeof HavuzIzolasyonCesmeRoute
  '/havuz-izolasyon-urla': typeof HavuzIzolasyonUrlaRoute
  '/hizmetler': typeof HizmetlerRoute
  '/iletisim': typeof IletisimRoute
  '/izolasyon-firmasi-bornova': typeof IzolasyonFirmasiBornovaRoute
  '/projelerimiz': typeof ProjelerimizRoute
  '/su-yalitimi-karsiyaka': typeof SuYalitimiKarsiyakaRoute
  '/teras-izolasyon-bornova': typeof TerasIzolasyonBornovaRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/hizmetler/$slug': typeof HizmetlerSlugRoute
  '/projelerimiz/$slug': typeof ProjelerimizSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/cati-izolasyon-bornova': typeof CatiIzolasyonBornovaRoute
  '/cati-izolasyon-karsiyaka': typeof CatiIzolasyonKarsiyakaRoute
  '/epoksi-zemin-cigli': typeof EpoksiZeminCigliRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/havuz-izolasyon-cesme': typeof HavuzIzolasyonCesmeRoute
  '/havuz-izolasyon-urla': typeof HavuzIzolasyonUrlaRoute
  '/hizmetler': typeof HizmetlerRoute
  '/iletisim': typeof IletisimRoute
  '/izolasyon-firmasi-bornova': typeof IzolasyonFirmasiBornovaRoute
  '/projelerimiz': typeof ProjelerimizRoute
  '/su-yalitimi-karsiyaka': typeof SuYalitimiKarsiyakaRoute
  '/teras-izolasyon-bornova': typeof TerasIzolasyonBornovaRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/hizmetler/$slug': typeof HizmetlerSlugRoute
  '/projelerimiz/$slug': typeof ProjelerimizSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/cati-izolasyon-bornova': typeof CatiIzolasyonBornovaRoute
  '/cati-izolasyon-karsiyaka': typeof CatiIzolasyonKarsiyakaRoute
  '/epoksi-zemin-cigli': typeof EpoksiZeminCigliRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/havuz-izolasyon-cesme': typeof HavuzIzolasyonCesmeRoute
  '/havuz-izolasyon-urla': typeof HavuzIzolasyonUrlaRoute
  '/hizmetler': typeof HizmetlerRoute
  '/iletisim': typeof IletisimRoute
  '/izolasyon-firmasi-bornova': typeof IzolasyonFirmasiBornovaRoute
  '/projelerimiz': typeof ProjelerimizRoute
  '/su-yalitimi-karsiyaka': typeof SuYalitimiKarsiyakaRoute
  '/teras-izolasyon-bornova': typeof TerasIzolasyonBornovaRoute
  '/blog_/$slug': typeof BlogSlugRoute
  '/hizmetler_/$slug': typeof HizmetlerSlugRoute
  '/projelerimiz_/$slug': typeof ProjelerimizSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/cati-izolasyon-bornova'
    | '/cati-izolasyon-karsiyaka'
    | '/epoksi-zemin-cigli'
    | '/hakkimizda'
    | '/havuz-izolasyon-cesme'
    | '/havuz-izolasyon-urla'
    | '/hizmetler'
    | '/iletisim'
    | '/izolasyon-firmasi-bornova'
    | '/projelerimiz'
    | '/su-yalitimi-karsiyaka'
    | '/teras-izolasyon-bornova'
    | '/blog/$slug'
    | '/hizmetler/$slug'
    | '/projelerimiz/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/cati-izolasyon-bornova'
    | '/cati-izolasyon-karsiyaka'
    | '/epoksi-zemin-cigli'
    | '/hakkimizda'
    | '/havuz-izolasyon-cesme'
    | '/havuz-izolasyon-urla'
    | '/hizmetler'
    | '/iletisim'
    | '/izolasyon-firmasi-bornova'
    | '/projelerimiz'
    | '/su-yalitimi-karsiyaka'
    | '/teras-izolasyon-bornova'
    | '/blog/$slug'
    | '/hizmetler/$slug'
    | '/projelerimiz/$slug'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/cati-izolasyon-bornova'
    | '/cati-izolasyon-karsiyaka'
    | '/epoksi-zemin-cigli'
    | '/hakkimizda'
    | '/havuz-izolasyon-cesme'
    | '/havuz-izolasyon-urla'
    | '/hizmetler'
    | '/iletisim'
    | '/izolasyon-firmasi-bornova'
    | '/projelerimiz'
    | '/su-yalitimi-karsiyaka'
    | '/teras-izolasyon-bornova'
    | '/blog_/$slug'
    | '/hizmetler_/$slug'
    | '/projelerimiz_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  CatiIzolasyonBornovaRoute: typeof CatiIzolasyonBornovaRoute
  CatiIzolasyonKarsiyakaRoute: typeof CatiIzolasyonKarsiyakaRoute
  EpoksiZeminCigliRoute: typeof EpoksiZeminCigliRoute
  HakkimizdaRoute: typeof HakkimizdaRoute
  HavuzIzolasyonCesmeRoute: typeof HavuzIzolasyonCesmeRoute
  HavuzIzolasyonUrlaRoute: typeof HavuzIzolasyonUrlaRoute
  HizmetlerRoute: typeof HizmetlerRoute
  IletisimRoute: typeof IletisimRoute
  IzolasyonFirmasiBornovaRoute: typeof IzolasyonFirmasiBornovaRoute
  ProjelerimizRoute: typeof ProjelerimizRoute
  SuYalitimiKarsiyakaRoute: typeof SuYalitimiKarsiyakaRoute
  TerasIzolasyonBornovaRoute: typeof TerasIzolasyonBornovaRoute
  BlogSlugRoute: typeof BlogSlugRoute
  HizmetlerSlugRoute: typeof HizmetlerSlugRoute
  ProjelerimizSlugRoute: typeof ProjelerimizSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teras-izolasyon-bornova': {
      id: '/teras-izolasyon-bornova'
      path: '/teras-izolasyon-bornova'
      fullPath: '/teras-izolasyon-bornova'
      preLoaderRoute: typeof TerasIzolasyonBornovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/su-yalitimi-karsiyaka': {
      id: '/su-yalitimi-karsiyaka'
      path: '/su-yalitimi-karsiyaka'
      fullPath: '/su-yalitimi-karsiyaka'
      preLoaderRoute: typeof SuYalitimiKarsiyakaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projelerimiz': {
      id: '/projelerimiz'
      path: '/projelerimiz'
      fullPath: '/projelerimiz'
      preLoaderRoute: typeof ProjelerimizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/izolasyon-firmasi-bornova': {
      id: '/izolasyon-firmasi-bornova'
      path: '/izolasyon-firmasi-bornova'
      fullPath: '/izolasyon-firmasi-bornova'
      preLoaderRoute: typeof IzolasyonFirmasiBornovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iletisim': {
      id: '/iletisim'
      path: '/iletisim'
      fullPath: '/iletisim'
      preLoaderRoute: typeof IletisimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hizmetler': {
      id: '/hizmetler'
      path: '/hizmetler'
      fullPath: '/hizmetler'
      preLoaderRoute: typeof HizmetlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/havuz-izolasyon-urla': {
      id: '/havuz-izolasyon-urla'
      path: '/havuz-izolasyon-urla'
      fullPath: '/havuz-izolasyon-urla'
      preLoaderRoute: typeof HavuzIzolasyonUrlaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/havuz-izolasyon-cesme': {
      id: '/havuz-izolasyon-cesme'
      path: '/havuz-izolasyon-cesme'
      fullPath: '/havuz-izolasyon-cesme'
      preLoaderRoute: typeof HavuzIzolasyonCesmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hakkimizda': {
      id: '/hakkimizda'
      path: '/hakkimizda'
      fullPath: '/hakkimizda'
      preLoaderRoute: typeof HakkimizdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epoksi-zemin-cigli': {
      id: '/epoksi-zemin-cigli'
      path: '/epoksi-zemin-cigli'
      fullPath: '/epoksi-zemin-cigli'
      preLoaderRoute: typeof EpoksiZeminCigliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cati-izolasyon-karsiyaka': {
      id: '/cati-izolasyon-karsiyaka'
      path: '/cati-izolasyon-karsiyaka'
      fullPath: '/cati-izolasyon-karsiyaka'
      preLoaderRoute: typeof CatiIzolasyonKarsiyakaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cati-izolasyon-bornova': {
      id: '/cati-izolasyon-bornova'
      path: '/cati-izolasyon-bornova'
      fullPath: '/cati-izolasyon-bornova'
      preLoaderRoute: typeof CatiIzolasyonBornovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projelerimiz_/$slug': {
      id: '/projelerimiz_/$slug'
      path: '/projelerimiz/$slug'
      fullPath: '/projelerimiz/$slug'
      preLoaderRoute: typeof ProjelerimizSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hizmetler_/$slug': {
      id: '/hizmetler_/$slug'
      path: '/hizmetler/$slug'
      fullPath: '/hizmetler/$slug'
      preLoaderRoute: typeof HizmetlerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/$slug': {
      id: '/blog_/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  CatiIzolasyonBornovaRoute: CatiIzolasyonBornovaRoute,
  CatiIzolasyonKarsiyakaRoute: CatiIzolasyonKarsiyakaRoute,
  EpoksiZeminCigliRoute: EpoksiZeminCigliRoute,
  HakkimizdaRoute: HakkimizdaRoute,
  HavuzIzolasyonCesmeRoute: HavuzIzolasyonCesmeRoute,
  HavuzIzolasyonUrlaRoute: HavuzIzolasyonUrlaRoute,
  HizmetlerRoute: HizmetlerRoute,
  IletisimRoute: IletisimRoute,
  IzolasyonFirmasiBornovaRoute: IzolasyonFirmasiBornovaRoute,
  ProjelerimizRoute: ProjelerimizRoute,
  SuYalitimiKarsiyakaRoute: SuYalitimiKarsiyakaRoute,
  TerasIzolasyonBornovaRoute: TerasIzolasyonBornovaRoute,
  BlogSlugRoute: BlogSlugRoute,
  HizmetlerSlugRoute: HizmetlerSlugRoute,
  ProjelerimizSlugRoute: ProjelerimizSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
